# Generated by Django 3.0.5 on 2021-03-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
